annotated-types==0.7.0
blis==1.0.1
catalogue==2.0.10
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
cloudpathlib==0.20.0
confection==0.1.5
cymem==2.0.8
es_core_news_sm @ https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.8.0/es_core_news_sm-3.8.0-py3-none-any.whl#sha256=e451a83d6df79b87e9eed0cb553f03e99e36a3bab18a7b79f0dcfd1fdf875e12
ffprobe==0.5
idna==3.10
Jinja2==3.1.4
langcodes==3.4.1
language_data==1.2.0
Levenshtein==0.26.1
marisa-trie==1.2.1
markdown-it-py==3.0.0
MarkupSafe==3.0.2
mdurl==0.1.2
murmurhash==1.0.10
numpy==2.0.2
packaging==24.2
preshed==3.0.9
pycparser==2.22
pydantic==2.9.2
pydantic_core==2.23.4
pydub==0.25.1
Pygments==2.18.0
RapidFuzz==3.10.1
requests==2.32.3
rich==13.9.4
setuptools==75.3.0
shellingham==1.5.4
smart-open==7.0.5
spacy==3.8.2
spacy-legacy==3.0.12
spacy-loggers==1.0.5
SpeechRecognition==3.11.0
srsly==2.4.8
srt==3.5.3
thinc==8.3.2
tqdm==4.66.6
typer==0.13.0
typing_extensions==4.12.2
urllib3==2.2.3
vosk==0.3.44
wasabi==1.1.3
weasel==0.4.1
websockets==13.1
wheel==0.44.0
wrapt==1.16.0
